sudo pip3 install btlewrap
sudo pip3 install miflora
sudo pip3 install bluepy
sudo pip3 install btlewrap
sudo pip3 install pexpect
sudo pip3 install requests
sudo pip3 install flask
sudo pip3 install flask_sqlalchemy
sudo pip3 install RPi.GPIO
